version: "3"
services:
  mongodb:
    image: mongo:4.2.15
    container_name: mongo-auditforge
    volumes:
      - ./backend/mongo-data:/data/db
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    environment:
      - MONGO_DB:auditforge
    networks:
      - backend

  auditforge-backend:
    build: ./backend
    image: auditforge-backend
    container_name: auditforge-backend
    volumes:
      - ./backend/report-templates:/app/report-templates
      - ./backend/src/config:/app/src/config
    depends_on:
      - mongodb
    restart: always
    ports:
      - 4242:4242
    links:
      - mongodb
    networks:
      - backend
      - cwe-api-network

  auditforge-frontend:
    build: ./frontend
    image: auditforge-frontend
    container_name: auditforge-frontend
    restart: always
    depends_on:
      - auditforge-backend
    ports:
      - 8443:8443
    networks:
      - backend

  auditforge-cwe-api:
    build:
      context: ./cwe_api
      dockerfile: Dockerfile
      args:
        FILE_ID: ${FILE_ID}
    image: auditforge-cwe-api
    container_name: auditforge-cwe-api
    restart: always
    networks:
      - cwe-api-network

volumes:
  mongo-data:

networks:
  backend:
    driver: bridge
  cwe-api-network:
    driver: bridge
