version: '3'
services:
  mongodb-test:
    image: mongo:4.2.15
    container_name: mongo-auditforge-test
    volumes:
      - ./mongo-data-test:/data/db
    restart: always
    environment:
      - MONGO_DB:auditforge
    network_mode: host

  backend-test:
    image: auditforge:backend-test
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: auditforge-backend-test
    volumes:
      - ./tests:/app/tests
      - ./src:/app/src
      - ./jest.config.js:/app/jest.config.js
    environment:
      API_URL: https://localhost:4242
    depends_on:
      - mongodb-test
    network_mode: host

volumes:
  mongo-data-test:
